server:
  port: 8088
k8s:
  api:
    # 是否启用
    enabled: true
    # 是否通过k8s内节点进行调用，为false则使用config-file调用
    in-cluster: false
    config-file: kubelet.conf
    log-enabled: true # 是否开启 k8s 的 HTTP 日志
    log-level: HEADERS # HTTP 日志级别，参考：HttpLoggingInterceptor.Level
